
CREATE TABLE ads
(
    id            bigint generated by default as identity
        primary key,
    description   varchar(255),
    price         integer not null,
    title         varchar(255),
    author_id     bigint,
    user_image_id bigint
);

create table public.comment
(
    id                integer generated by default as identity
        primary key,
    author            integer not null,
    author_first_name varchar(255),
    author_image      varchar(255),
    created_at        integer not null,
    text              varchar(255),
    pk                integer not null
);

create table user_image
(
    id         bigint generated by default as identity
        primary key,
    file_size  bigint,
    image      bytea,
    media_type varchar(255),
    title      varchar(255),
    user_id    bigint
);

create table users
(
    id         bigint generated by default as identity
        primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    phone      varchar(255),
    role       integer,
    username   varchar(255),
    image_id   bigint
);
