
CREATE TABLE ads
(
    id            bigint generated by default as identity
        primary key,
    description   varchar(255),
    price         integer not null,
    title         varchar(255),
    author_id     bigint,
    user_image_id bigint
);

create table comment
(
    pk              integer generated by default as identity
        primary key,
    created_at      timestamp,
    text            varchar(255),
    id              bigint,
    first_name      bigint,
    author_image_id bigint
);

create table user_image
(
    id         bigint generated by default as identity
        primary key,
    file_size  bigint,
    image      bytea,
    media_type varchar(255),
    title      varchar(255),
    user_id    bigint
);

create table users
(
    id         bigint generated by default as identity
        primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    phone      varchar(255),
    role       integer,
    username   varchar(255),
    image_id   bigint
);
